// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class FalsoPositivo
{
    public string SOfensa { get; set; }

    public string SPalavra { get; set; }
}